# 1.7 Introduction to Numpy
plan:
- creating arrays
- randomly generated arrays
- Element-wise operations
- comparison operations
- logical operations
- summarizing operation

In [2]:
import numpy as np

## Creating arrays


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

In [5]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dementional arrays

In [3]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Randomly generated arrays

In [8]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [9]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [12]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [14]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [18]:
b= (10+(a*1)) **2 /10

In [19]:
a+b

array([10. , 13.1, 16.4, 19.9, 23.6])

## comparison operations

In [20]:
a >=2

array([False, False,  True,  True,  True])

In [21]:
b>a

array([False, False, False, False, False])

In [24]:
a[b>a]

array([0, 1, 2, 3, 4])

## Sunnarizing Operations

In [25]:
a.max()

4

In [27]:
a.std()

1.4142135623730951